website/routes.py
from flask import Blueprint, redirect, render_template, request, session, url_for
from user_info import reset_user_password, save_user_credentials, authenticate_user, get_user_balance, update_user_balance, get_user_loan, update_user_loan, get_user_info
from user_transactions import load_user_transactions, add_user_transaction
from database import user_collection
from datetime import datetime

auth = Blueprint('auth', __name__)   
date_time = datetime.now()
proper_datetime = date_time.strftime("%H:%M | %Y-%m-%d")

def validate_password(password):
    has_number = any(char.isdigit() for char in password)
    has_special = any(char in "!@#$%^&*()-_=+" for char in password)
    return has_number and has_special

@auth.route("/", methods=["GET"])
def start():
    return render_template("front_page.html")

@auth.route("/about")
def about():
    return render_template("about.html")

@auth.route("/logout")
def logout():
    session.clear()
    return redirect(url_for('auth.start'))

@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")
        username_lower = username.lower()

        if authenticate_user(username_lower, password):
            session['username'] = username
            return redirect(url_for("auth.accountPage"))
        else:
            return render_template("login.html", message="Login failed, Please check your user credentials")

    return render_template("login.html")

@auth.route("/resetPassword", methods=["GET", "POST"])
def reset_password():
    if request.method == "POST":
        username = request.form.get("username")
        secret_word = request.form.get("secret_word")
        new_password = request.form.get("password")

        if not username:
            return render_template("forgot_password.html", message="Username is not provided")

        if not secret_word:
            return render_template("forgot_password.html", message="Secret word is not provided")

        if new_password:
            if not validate_password(new_password):
                return render_template("register.html", message="Password must contain at least one special character and one number")

            resetted = reset_user_password(username, secret_word, new_password)

            if resetted:
                return render_template("forgot_password.html", message="Password successfully changed")
            else:
                return render_template("forgot_password.html", message="Username or/and secret word was incorrect")
        else:
            return render_template("forgot_password.html", message="Password is not provided")

    return render_template("forgot_password.html", message="ERROR: UNEXPECTED")

@auth.route("/registration", methods=["GET", "POST"])
def registration():
    if request.method == "POST":
        new_username = request.form.get("username")
        new_password = request.form.get("password")
        
        if user_collection.find_one({"username": new_username.lower()}):
            return render_template("register.html", message="Username is already taken")
        
        if new_password:
            if not validate_password(new_password):
                return render_template("register.html", message="Password must contain at least one special character and one number")

        save_user_credentials(new_username, new_password)
        return redirect(url_for("auth.login"))

    return render_template("register.html")

@auth.route("/accountpage", methods=["GET"])
def accountPage():
    username = session.get('username')
    user_data = user_collection.find_one({"username": username})

    if user_data:
        # Retrieves user information within database and sets it in current session
        loan = "{:,}".format(user_data["loan"])
        session['loan'] = user_data["loan"]
        secret_word = user_data["secret_word"]
        session['secret_word'] = secret_word
        checking_balance = "{:,}".format(user_data["checking_balance"])
        session['checking_balance'] = user_data["checking_balance"]
        savings_balance = "{:,}".format(user_data["savings_balance"])
        session['savings_balance'] = user_data["savings_balance"]
        
        return render_template("account_page.html", user=username, checking_balance=checking_balance, savings_balance=savings_balance, loan=loan, secret_word=secret_word)
    else:
        return render_template("account_page.html", message="User not found")

@auth.route("/deposit", methods=["GET", "POST"])
def deposit():
    if request.method == "POST":
        amount = request.form.get("amount")
        account_type = request.form.get("account_type")
        username = session.get('username')

        try:
            amount = float(amount)
        except ValueError:
            return render_template("deposit.html", message="Incorrect Input")

        if amount <= 0:
            return render_template("deposit.html", message="Invalid Amount")

        checking_balance = get_user_balance(username, "checking")
        savings_balance = get_user_balance(username, "savings")

        if account_type == "checking":
            new_balance = checking_balance + amount
        elif account_type == "savings":
            new_balance = savings_balance + amount

        update_user_balance(username, account_type, new_balance)
        add_user_transaction(username, f"({proper_datetime}) - Deposited ${amount} into your {account_type} account")

        checking_balance = get_user_balance(username, "checking")
        savings_balance = get_user_balance(username, "savings")

        return render_template("deposit.html", checking_balance=checking_balance, savings_balance=savings_balance, message=f"Deposited ${amount} into your {account_type} account")
    
    return render_template("deposit.html", checking_balance=session.get("checking_balance"), savings_balance=session.get("savings_balance"))

@auth.route("/withdraw", methods=["GET", "POST"])
def withdraw():
    if request.method == "POST":
        amount = request.form.get("amount")
        account_type = request.form.get("account_type")
        username = session.get('username')

        try:
            amount = float(amount)
        except ValueError:
            return render_template("withdrawal.html", message="Incorrect Input")

        if amount <= 0:
            return render_template("withdrawal.html", message="Invalid Amount")

        checking_balance = get_user_balance(username, "checking")
        savings_balance = get_user_balance(username, "savings")

        if account_type == "checking" and amount > checking_balance:
            return render_template("withdrawal.html", message="Insufficient Balance")
        elif account_type == "savings" and amount > savings_balance:
            return render_template("withdrawal.html", message="Insufficient Balance")

        if account_type == "checking":
            new_balance = checking_balance - amount
        elif account_type == "savings":
            new_balance = savings_balance - amount

        update_user_balance(username, account_type, new_balance)
        add_user_transaction(username, f"({proper_datetime}) - Withdrawn ${amount} from your {account_type} account")

        checking_balance = get_user_balance(username, "checking")
        savings_balance = get_user_balance(username, "savings")

        return render_template("withdrawal.html", checking_balance=checking_balance, savings_balance=savings_balance, message=f"Withdrawn ${amount} from your {account_type} account")

    return render_template("withdrawal.html", checking_balance=session.get("checking_balance"), savings_balance=session.get("savings_balance"))

@auth.route("/transactions")
def transactions():
    username = session.get('username')
    user_transactions = load_user_transactions(username)
    return render_template("transactions.html", transactions=user_transactions)

@auth.route("/loans")
def loans():
    return render_template("loans.html")

@auth.route("/pay_loan", methods=["GET", "POST"])
def pay_loan():
    username = session.get('username')
    loan = get_user_loan(username)  
    checking_balance = get_user_balance(username, "checking") 

    if request.method == "POST":
        amount = request.form.get("amount")

        try:
            amount = float(amount)
        except ValueError:
            return render_template("pay_loan.html", loan=loan, checking_balance=checking_balance, message="Incorrect Input")

        if amount <= 0:
            return render_template("pay_loan.html", loan=loan, checking_balance=checking_balance, message="Invalid Amount")

        if amount > loan:
            return render_template("pay_loan.html", loan=loan, checking_balance=checking_balance, message="Cannot pay more than loan amount")
        
        current_checking_balance = get_user_balance(username, "checking")
        new_balance = current_checking_balance - amount
        update_user_balance(username, "checking", new_balance)

        new_loan = loan - amount
        update_user_loan(username, new_loan)

        add_user_transaction(username, f"({proper_datetime}) - Paid ${amount} of your loan")

        return render_template("pay_loan.html", loan=loan, checking_balance=new_balance, message=f"Paid ${amount} of your loan")

    return render_template("pay_loan.html", loan=loan, checking_balance=checking_balance)

@auth.route("/request_loan", methods=["GET", "POST"])
def request_loan():
    username = session.get('username')
    loan = get_user_loan(username)  
    checking_balance = get_user_balance(username, "checking")  

    if request.method == "POST":
        amount = request.form.get("amount")

        try:
            amount = float(amount)
        except ValueError:
            return render_template("request_loan.html", loan=loan, checking_balance=checking_balance, message="Incorrect Input")

website/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>About</title>
    <link rel="stylesheet" href="static/front_page.css">
    <link rel="stylesheet" href="static/styles.css">
    <link rel="stylesheet" href="static/icons.css">
</head>
<body>
    <div class="top-section">
      <h1 class="name-header">About</h1>
        <nav class="navigation-bar">
          <ul class="navigation-buttons">
            <li><a href="{{ url_for('auth.login') }}">Start</a></li>
            <li><a href="{{ url_for('auth.login') }}">Login</a></li>
            <li><a href="{{ url_for('auth.registration') }}">Register</a></li>
          </ul>
        </nav>
    </div>
    <div class="middle-section">
        <div class='video_box'>
        <p class="info_box_message">Us!</p>
        <iframe class="featured_video" width="640" height="360" src="https://www.youtube.com/embed/zOuhAPypcSg" frameborder="0" allowfullscreen></iframe>
      </div>
      <div class="info_box">
        <img class="happy_guy" src="static/images/united.jpg">
        <p class="info_box_message">Our team will assist you with any needs!</p>
      </div>
    </div>
      <div class="bottom-section">
        <h1 class="trusted_bank_label">The most trusted bank in America</h1>
        <div class="icon_container">
          <img class="money_icon" src="static/images/money-icon.png">
          <img class="employee_icon" src="static/images/bank-employee.png">
          <img class="stocks_icon" src="static/images/stocks-icon.png">
        </div>
        <div>
          <div id="social-media-row">
            <a href="https://twitter.com/"><button id="twitter-icon" class="image-button" title="Follow us on Twitter!"></button></a>
            <a href="https://facebook.com/"><button id="facebook-icon" class="image-button" title="Follow us on Facebook!"></button></a>
            <a href="https://instagram.com/"><button id="instagram-icon" class="image-button" title="Follow us on Instagram!"></button></a>
            <a href="https://github.com/darrencodes0"><button id="github-icon" class="image-button" title="Follow me on GitHub!"></button></a>
            <a href="https://youtube.com/"><button id="youtube-icon" class="image-button" title="Follow us on YouTube!"></button></a>
          </div>
          <h1 class="bottom_label">Deposit, Withdraw, Transactions</h1>
        </div>
      </div>
    
      <script src="{{ url_for('static', filename='transfer_confirmation.js') }}"></script>
</body>
</html>

website/templates/account_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Account Page</title>
    <link rel="stylesheet" href="static/styles.css">
    <link rel="stylesheet" href="static/account_page.css">
    <link rel="stylesheet" href="static/icons.css">
</head>
<body>
    <div class="top-section">
        <h1 class="name-header">Welcome, {{ user }}!</h1>
    </div>
    <div class="middle-section">
        <div class="form-set">
            <label for="" id="checking_account_label" class="bank-info">Checking Account Balance: ${{ checking_balance }}</label>
            <p class="bank-info-label">${{ checking_balance }}</p>
            <label for="" id="savings_account_label" class="bank-info">Savings Account Balance: ${{ savings_balance }}</label>
            <p class="bank-info-label">${{ savings_balance }}</p>
        </div>
        <div class="form-set">
            <label for="" class="bank-info">Loans owed: ${{ loan }}</label>
            <p class="bank-info-label">This is the current amount in loans that you owe</p>
        </div>
        <div class="form-set">
            <label for="">What would you like to do?</label>
        </div>
        <div class="account-options">
            <div>
                <a href="{{ url_for('auth.deposit') }}">
                <button class="bank-button" id="deposit-button" type="submit">Deposit Money</button>
                <p class="bank-info-label">Deposit money into your account</p>

                </a>
            </div>
            <div>
                <a href="{{ url_for('auth.withdraw') }}">
                <button class="bank-button" id="withdraw-button" type="submit">Withdraw Money</button>
                <p class="bank-info-label">Withdraw money from your account</p>

                </a>
            </div>
            <div>
                <a href="{{ url_for('auth.transactions') }}">
                <button class="bank-button" type="submit">View Transactions</button>
                <p class="bank-info-label">View all your transactions here</p>


                </a>
            </div>
            <div>
                <a href="{{ url_for('auth.loans') }}">
                <button class="bank-button" type="submit">Request/Pay a Loan</button>
                <p class="bank-info-label">Request or Pay off a loan here</p>

                </a>
            </div>
            <div>
                <a href="{{ url_for('auth.transfer') }}">
                <button class="bank-button">Transfer Money</button>
                <p class="bank-info-label">Transfer money between your checkings and savings account</p>
                </a>
            </div>
            <div>
                <a href="{{ url_for('auth.send_money') }}">
                <button class="bank-button">Send Money</button>
                <p class="bank-info-label">Send money to a existing user account</p>
                </a>
            </div>
            <div>
                <a href="{{ url_for('auth.logout') }}">
                <button class="bank-button">Log out</button>
                <p class="bank-info-label">Log out of your account</p>

                </a>
            </div>
                <div id="secret_word" title="IMPORTANT: Make sure you remember this so you can reset your password!">Your secret word to reset password: {{ secret_word }}</div>
        </div>
    </div>

    <div class="bottom-section">
        <h1 class="trusted_bank_label">The most trusted bank in America</h1>
        <div class="icon_container">
          <img class="money_icon" src="static/images/money-icon.png">
          <img class="employee_icon" src="static/images/bank-employee.png">
          <img class="stocks_icon" src="static/images/stocks-icon.png">
        </div>
        <div id="social-media-row">
          <a href="https://twitter.com/"><button id="twitter-icon" class="image-button" title="Follow us on Twitter!"></button></a>
          <a href="https://facebook.com/"><button id="facebook-icon" class="image-button" title="Follow us on Facebook!"></button></a>
          <a href="https://instagram.com/"><button id="instagram-icon" class="image-button" title="Follow us on Instagram!"></button></a>
          <a href="https://github.com/darrencodes0"><button id="github-icon" class="image-button" title="Follow me on GitHub!"></button></a>
          <a href="https://youtube.com/"><button id="youtube-icon" class="image-button" title="Follow us on YouTube!"></button></a>
        </div>
        <h1 class="bottom_label">Deposit, Withdraw, Transactions</h1>
        <p class="bottom_label">This website is just a fun little project created by Darren</p>
      </div>
  
    <script src="{{ url_for('static', filename='auto_logout.js') }}"></script>
</body>
</html>

website/templates/forgot_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bank Account Login</title>
    <link rel="stylesheet" href="static/styles.css">
    <link rel="stylesheet" href="static/forgot_password.css">

</head>
<body>
    <div class="top-section">
      <h1 class="name-header">Forgot Password</h1>
    </div>
    <div class="middle-section">
      <form method="POST" action="{{ url_for('auth.reset_password') }}">
        <div class="form-set">
          <label for="username" class="form__label bank-info">Username:</label>
          <input type="text" name="username" id="username" class="form__label">
        </div>
      
        <div class="form-set">
          <label for="secret_word" class="form__label bank-info">Secret Word to Reset Password:</label>
          <input type="text" name="secret_word" id="secret_word" class="form__label">
        </div>

        <div class="form-set">
          <label for="password" class="form__label bank-info">New Password:</label>
          <input type="password" name="password" id="password" class="form__label">
          <button type="button" onclick="togglePassword()" class="togglePassword">Toggle Password</button>
        </div>
      
        <div class="form-set">
          <input class="bank-button" type="submit" value="Reset">
          <a href="{{ url_for('auth.login') }}" class="bank-button">Back</a>
        </div>
      </form>
        <div class="container top-half">
          {% if message %}
          <p class="text" >{{ message }}</p>
        {% endif %}
      </div>
    </div>
    
    <div class="bottom-section">
      <h1 class="trusted_bank_label">The most trusted bank in America</h1>
      <div class="icon_container">
        <img class="money_icon" src="static/images/money-icon.png">
        <img class="employee_icon" src="static/images/bank-employee.png">
        <img class="stocks_icon" src="static/images/stocks-icon.png">
      </div>
      <div>
        <h1 class="bottom_label">Deposit, Withdraw, Transactions</h1>
      </div>
    </div>

    <script src="static/toggle_password.js"></script> 
</body>
</html>

website/templates/frontpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home</title>
    <link rel="stylesheet" href="static/styles.css">
    <link rel="stylesheet" href="static/frontpage.css">
</head>
<body>
    <div class="top-section">
      <h1 class="name-header">My Bank</h1>
        <nav class="navigation-bar">
          <ul class="navigation-buttons">
            <li><a href="{{ url_for('auth.login') }}">Start</a></li>
            <li><a href="{{ url_for('auth.login') }}">Login</a></li>
            <li><a href="{{ url_for('auth.registration') }}">Register</a></li>
            <li><a href="{{ url_for('auth.about') }}">About</a></li>
          </ul>
        </nav>
    </div>
    <div class="middle-section">
        <div class='video_box'>
        <p class="info_box_message">Exclusive video from our sponser!</p>
        <iframe class="featured_video" width="640" height="360" src="https://www.youtube.com/embed/MZBeYSfIrLg" frameborder="0" allowfullscreen></iframe>
      </div>
      <div class="info_box">
        <img class="happy_guy" src="static/images/guyhappy.jpg">
        <p class="info_box_message">Solve any financial problems at a touch of a button!</p>
      </div>
        <a href="{{ url_for('auth.login') }}" class="get_started_button">Get Started</a>
    </div>
      <div class="bottom-section">
        <h1 class="trusted_bank_label">The most trusted bank in America</h1>
        <div class="icon_container">
          <img class="money_icon" src="static/images/money-icon.png">
          <img class="employee_icon" src="static/images/bank-employee.png">
          <img class="stocks_icon" src="static/images/stocks-icon.png">
        </div>
        <div>
          <h1 class="bottom_label">Deposit, Withdraw, Transactions</h1>
          <p class="bottom_label">This website is just a fun little project created by Darren</p>
        </div>
      </div>
    
</body>
</html>

website/templates/loans.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Loans</title>
    <link rel="stylesheet" href="static/styles.css">
    <link rel="stylesheet" href="static/loans.css">

</head>
<body>
    <div class="top-section">
      <h1 class="name-header">Loans</h1>
    </div>
    <div class="middle-section">
      <img class="loan_icon" src="static/images/loan-icon.png">

      <a href="{{ url_for('auth.pay_loan') }}">
        <button class="bank-button" id="withdraw-button" type="submit">Pay Loan</button>
        </a>
      
      <a href="{{ url_for('auth.request_loan') }}">
        <button class="bank-button" id="withdraw-button" type="submit">Request Loan</button>
        </a>
      
      <a href="{{ url_for('auth.accountPage') }}" class="bank-button back-button">Back</a>
    </div>

    <div class="bottom-section">
      <h1 class="trusted_bank_label">The most trusted bank in America</h1>
      <div class="icon_container">
          <img class="money_icon" src="static/images/money-icon.png">
          <img class="employee_icon" src="static/images/bank-employee.png">
          <img class="stocks_icon" src="static/images/stocks-icon.png">
      </div>
      <div>
          <h1 class="bottom_label">Deposit, Withdraw, Transactions</h1>
      </div>
      </div>      
    <script src="{{ url_for('static', filename='auto_logout.js') }}"></script>

</body>
</html>

website/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bank Account Login</title>
    <link rel="stylesheet" href="static/styles.css">
    <link rel="stylesheet" href="static/login.css">

</head>
<body>
    <div class="top-section">
      <h1 class="name-header">Login</h1>
    </div>
    <div class="middle-section">
      <form method="POST" action="{{ url_for('auth.login') }}">
        <div class="form-set">
          <label for="username" class="form__label bank-info">Username:</label>
          <input type="text" name="username" id="username" class="form__label">
        </div>
      
        <div class="form-set">
          <label for="password" class="form__label bank-info">Password:</label>
          <input type="password" name="password" id="password" class="form__label">
          <button type="button" onclick="togglePassword()" class="togglePassword">Toggle Password</button>
        </div>
      
        <div class="form-set">
          <input class="bank-button" type="submit" value="Login">
          <a href="{{ url_for('auth.registration') }}" class="bank-button">Register</a>
        </div>
      </form>
        <div class="container top-half">
          {% if message %}
          <p class="text" >{{ message }}</p>
        {% endif %}
      </div>
      <a class="no-account-link" href="{{ url_for('auth.registration') }}">Don't have an account yet?</a>
      <a class="forgot-password-link" href="{{ url_for('auth.reset_password') }}">Forgot Password?</a>
    </div>
    
    <div class="bottom-section">
      <h1 class="trusted_bank_label">The most trusted bank in America</h1>
      <div class="icon_container">
        <img class="money_icon" src="static/images/money-icon.png">
        <img class="employee_icon" src="static/images/bank-employee.png">
        <img class="stocks_icon" src="static/images/stocks-icon.png">
      </div>
      <div>
        <h1 class="bottom_label">Deposit, Withdraw, Transactions</h1>
      </div>
    </div>

    <script src="static/toggle_password.js"></script> 
</body>
</html>

website/templates/pay_loan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Paying Loan</title>
    <link rel="stylesheet" href="static/styles.css">
    <link rel="stylesheet" href="static/pay_loan.css">
</head>
<body>
    <div class="top-section">
      <h1 class="name-header">Paying off loan</h1>
    </div>

    <div class="middle-section">
    <img class="loan_icon" src="static/images/loan-signing.png">

    <p class="bank-info">Loan amount owed: {{loan}}$</p>
    <p><span class="bank-info">Checking Account Balance: ${{ checking_balance }}</span></p>
    <form method="POST">   
      <div class="form-set">
        <label for="amount" class="form__label">Amount to Pay:</label>
        <input type="number" name="amount" id="amount" class="form__label" step="0.01" min="0.01">
      </div>

      <input type="hidden" id="account_type" name="account_type" value="checking">

      <div class="form-set">
        <input class="bank-button" type="submit" value="Pay" step="0.01" min="0.01">
        <a href="{{ url_for('auth.loans') }}" class="bank-button">Back</a>
      </div>
    </form>

    <div>
      {% if message %}
        <p class="text">{{ message }}</p>
    {% endif %}
    </div>
  </div>

    <div class="bottom-section">
      <h1 class="trusted_bank_label">The most trusted bank in America</h1>
      <div class="icon_container">
        <img class="money_icon" src="static/images/money-icon.png">
        <img class="employee_icon" src="static/images/bank-employee.png">
        <img class="stocks_icon" src="static/images/stocks-icon.png">
      </div>
      <div>
        <h1 class="bottom_label">Deposit, Withdraw, Transactions</h1>
      </div>
    </div>

    <script src="{{ url_for('static', filename='auto_logout.js') }}"></script>
</body>
</html>

website/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Registration</title>
    <link rel="stylesheet" href="static/styles.css"></link>
    <link rel="stylesheet" href="static/register.css"></link>
  </head>
<body>
    <div class="top-section">
        <h1 class="name-header">Registration</h1>
    </div>
    <div class="middle-section">
        <form method="POST" action="{{ url_for('auth.registration') }}">
            <div class="form-set">
                <label for="username" class="form__label bank-info">Username:</label>
                <input type="text" name="username" id="username" class="form__label">
            </div>

            <div class="form-set">
                <label for="password" class="form__label bank-info">Password:</label>
                <input type="password" name="password" id="password" class="form__label">
                <button type="button" onclick="togglePassword()" class="togglePassword">Toggle Password</button>
            </div>

            <div class="form-set">
                <input class="bank-button" type="submit" value="Register">
                <a href="{{ url_for('auth.login') }}" class="bank-button">Back</a>
            </div>
        </form>
        <div>{% if message %}
            <p class="text">{{ message }}</p>
        {% endif %}
        </div>
        <a class="have-account-link" href="{{ url_for('auth.login') }}">Already have an account?</a>
    </div>

    <div class="bottom-section">
        <h1 class="trusted_bank_label">The most trusted bank in America</h1>
        <div class="icon_container">
            <img class="money_icon" src="static/images/money-icon.png">
            <img class="employee_icon" src="static/images/bank-employee.png">
            <img class="stocks_icon" src="static/images/stocks-icon.png">
        </div>
        <div>
            <h1 class="bottom_label">Deposit, Withdraw, Transactions</h1>
        </div>
    </div>

    <script src="static/toggle_password.js"></script> 
</body>
</html>

website/templates/request_loan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Request Loan</title>
    <link rel="stylesheet" href="static/styles.css">   
    <link rel="stylesheet" href="static/request_loan.css">
</head>
<body>
    <div class="top-section">
      <h1 class="name-header">Request Loan</h1>
    </div>
    <div class="middle-section">
      <div class="info-box">
        <img class="loan_icon" src="static/images/loan-icon2.png">
        <p id="fixed-loan-label">! We have a fixed loan interest rate at 18% !</p>
        <p id="loans-rounded-label">Loans will be rounded to the nearest dollar</p>
        <p class="bank-info">Loan amount owed: {{loan}}$</p>
        <p><span class="bank-info">Checking Account Balance: ${{ checking_balance }}</span></p>
      <form method="POST">   
        <div class="form-set">
          <label for="amount" class="form__label">Request Amount:</label>
          <input type="number" name="amount" id="amount" class="form__label" step="0.01" min="0.01">
        </div>

        <div class="form-set">
          <input class="bank-button" type="submit" value="Request" step="0.01" min="0.01">
          <a href="{{ url_for('auth.loans') }}" class="bank-button">Back</a>
        </div>
     </div>
    </form>

    <div class="container top-half">
      {% if message %}
        <p class="text">{{ message }}</p>
    {% endif %}
      {% if loan_given %}
        <p class="text">{{ loan_given }}</p>
    {% endif %}
    </div>
    </div>
  
    <div class="bottom-section">
      <h1 class="trusted_bank_label">The most trusted bank in America</h1>
      <div class="icon_container">
        <img class="money_icon" src="static/images/money-icon.png">
        <img class="employee_icon" src="static/images/bank-employee.png">
        <img class="stocks_icon" src="static/images/stocks-icon.png">
      </div>
      <div>
        <h1 class="bottom_label">Deposit, Withdraw, Transactions</h1>
      </div>
    </div>

    <script src="{{ url_for('static', filename='auto_logout.js') }}"></script>

</body>
</html>

website/templates/transactions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Transactions</title>
    <link rel="stylesheet" href="static/styles.css">
    <link rel="stylesheet" href="static/transactions.css">
</head>
<body>
  <div class="top-section">
    <h1 class="name-header">Account Transactions</h1>
  </div>
  <div class="middle-section">
    {% if transactions %}
      <ul class="transaction-list">
        {% for transaction in transactions %}
          <li><span class="transaction-label">{{ transaction }}</span></li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No transactions available.</p>
    {% endif %}
    <a href="{{ url_for('auth.accountPage') }}" class="bank-button">Back</a>
  </div>

  <script src="{{ url_for('static', filename='auto_logout.js') }}"></script>

</body>
</html>